package com.fundagent.core.trace;

public enum TraceEventType {
    EPISODE_CREATED,
    EPISODE_STARTED,
    EPISODE_WAITING_USER,
    EPISODE_WAITING_CONFIRMATION,
    EPISODE_COMPLETED,
    EPISODE_FAILED,
    EPISODE_ABORTED,
    EPISODE_RESULT_UNKNOWN,
    EPISODE_SEALED,

    CONTEXT_ASSEMBLED,
    PLAN_REQUESTED,
    PLAN_GENERATED,
    PLAN_VALIDATED,
    PLAN_REJECTED,

    CAPABILITY_SELECTED,
    TOOL_BINDING_STARTED,
    TOOL_BOUND,
    TOOL_BINDING_FAILED,

    NODE_READY,
    NODE_STARTED,
    NODE_COMPLETED,
    NODE_FAILED,
    NODE_SKIPPED,
    NODE_WAITING_USER,
    NODE_VERIFIED,

    MODEL_CALL_STARTED,
    MODEL_CALL_COMPLETED,
    MODEL_CALL_FAILED,
    MODEL_OUTPUT_REJECTED,

    POLICY_CHECK_STARTED,
    POLICY_ALLOWED,
    POLICY_DENIED,
    CONFIRMATION_REQUESTED,
    CONFIRMATION_RECEIVED,
    CONFIRMATION_REJECTED,

    TOOL_CALL_INTENT_RECORDED,
    TOOL_CALL_STARTED,
    TOOL_CALL_SUCCEEDED,
    TOOL_CALL_FAILED,
    TOOL_CALL_RESULT_UNKNOWN,

    EVIDENCE_COLLECTED,
    EVIDENCE_REJECTED,
    GOAL_VERIFICATION_STARTED,
    GOAL_VERIFICATION_PASSED,
    GOAL_VERIFICATION_FAILED,
    GOAL_VERIFICATION_INCONCLUSIVE,

    RECOVERY_DECIDED,
    RETRY_SCHEDULED,
    REPLAN_STARTED,
    REPLAN_GENERATED,
    REPLAN_REJECTED,
    HUMAN_REVIEW_REQUESTED
}
